name: telegramarr

services:
  telegramarr:
    container_name: telegramarr
    image: ghcr.io/funkykwak/telegramarr:latest
    volumes:
      - path_to_telegramarr:/app/data
    environment:
      - SEERR_HOST=${SEERR_HOST:-seerr}
      - SEERR_PORT=${SEERR_PORT:-5055}
      - SEERR_API_KEY=${SEERR_API_KEY}

      - PROWLARR_HOST=${PROWLARR_HOST:-prowlarr}
      - PROWLARR_PORT=${PROWLARR_PORT:-9696}
      - PROWLARR_API_KEY=${PROWLARR_API_KEY}

      - TMDB_API_KEY=${TMDB_API_KEY}

      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

      - LOOP_INTERVAL_HOURS=${LOOP_INTERVAL_HOURS:-1}
      - SEARCH_INTERVAL_HOURS_PER_MOVIE=${SEARCH_INTERVAL_HOURS_PER_MOVIE:-6}
    restart: unless-stopped
